### ISSUE TITLE
Attach calculatable schema?

### ISSUE THREAD

**Issue by ivansglazunov** [aldeed/meteor-collection2-core#10]
```js
new SimpleSchema({
  type: () => new SimpleSchema(Schemas.findOne(this.field('schema')))
});
```

* Why not?
* How?

**Comment by aldeed** [comment]
There are a lot of places where we need the `type` in advance of validating. With some large effort this maybe could be supported, but I don't think it's worth it. Instead, you can use the existing multi-schema support like:

```js
Schemas.find().forEach(schema => {
  collection.attachSchema(new SimpleSchema(schema), { selector: { schema: schema._id } });
});
```
