### ISSUE TITLE
How to use ValidateOne for array?

### ISSUE THREAD

**Issue by ivansglazunov** [aldeed/meteor-collection2-core#11]
```js
var s = new SimpleSchema({
  'field': {
    type: Array
  },
  'field.$': {
    type: String
  }
});
var c = s.newContext();
c.validateOne({ $push: { 'field': 123 } }, 'field', { modifier: true }); // true
```

**Comment by benlavalley** [comment]
Based on the documentation for the new version of simple-schema used by collection2-core:
[](https://github.com/aldeed/meteor-simple-schema/blob/v2/CHANGELOG.md#200)

> Removed: validationContext.validateOne(): Instead you can pass a keys array as an option to validationContext.validate().
