### ISSUE TITLE
$push to Array doesn't add default values

### ISSUE THREAD

**Issue by Floriferous** [aldeed/meteor-collection2-core#15]
I have a schema with an array of objects, and that object is defined with a few non-optional defaultValues. I'd like to be able to $push an empty object to that array and have it automatically populated with all the necessary defaultValues, but instead it throws an error

`Exception while invoking method 'methodName' Error: My field is required`

Not sure if this is consistent with the insert behaviour?

**Comment by MaxGuitet** [comment]
In SimpleSchema doc about `defaultValue`

> Used by the cleaning process but not by validation

If I understand you issue, you want to populate on validation, which will not happen. To have the default values used, you can either set the fields to be optional or manually run the cleaning process before validating your object.
