### ISSUE TITLE
Error: _schema key is missing "type"

### ISSUE THREAD

**Issue by chellem** [aldeed/meteor-collection2-core#16]
Hello,
Am trying to define a schema for a collection. Am getting the following errors:

> Exception in callback of async function: Error: _schema key is missing "type"
> in file **simpl-schema/dist/SimpleSchema.js:858:26**

**Comment by chellem** [comment]
After removing `aldeed:simple-schema`, I got the following error:

> Error: _constructorOptions key is missing "type"

**Comment by Neko2h** [comment]
Got the same error

**Comment by vlasy** [comment]
I have the same problem

**Comment by fuatsengul** [comment]
Getting same error...

**Comment by Zaridias** [comment]
Getting the same error as well.

**Comment by nidem** [comment]
I had this until I fully removed the old `aldeed:collections2` package. Some other packages will hold onto it so make sure you fully remove those dependencies. `meteor list` doesn't show the hidden dependency. :/

If you remove collections2, autoform and any other packages that use `aldeed:collections2` you should get an error that `SimpleSchema` is undefined. This is what you want! 

Then follow the directions in the readme
```
$ meteor add aldeed:collection2-core
$ meteor npm install --save simpl-schema
```

Add the other packages back in (one at a time) and test to make sure you are getting the error that `SimpleSchema` is undefined. Then, add the `import` to each Scheme and you should be ready to rock and roll.

**Comment by evan-ritchie** [comment]
Above solution from @nidem worked for me.  Please note that you must have the following line in your code for it to work:

`import SimpleSchema from 'simpl-schema';`

Also if you are using with autoform, I had to add this below the line above:

`SimpleSchema.extendOptions(['autoform']);`

**Comment by aldeed** [comment]
Yeah, unfortunately this can get tricky but @nidem's solution is correct. Just make sure the old packages disappear from the `.meteor/versions` file and don't reappear when you run the app. If you use add-on packages, you might have to disable them temporarily and ask the authors to publish releases that work with the newer packages.
