### ISSUE TITLE
Not compatible with Meteor 1.4.2.7??

### ISSUE THREAD

**Issue by carlosalvidrez** [aldeed/meteor-collection2-core#17]
I got this error message when trying to upgrade the package to its latest version (2.0).
Please help.. I want to make sure I can still use the package.

$ meteor update
This project is already at Meteor 1.4.2.7, the latest release.
Your top-level dependencies are at their latest compatible versions.
                                              
Newer versions of the following indirect dependencies are available:
 * aldeed:collection2-core 1.2.0 (2.0.0 is available)
 * aldeed:schema-deny 1.1.0 (2.0.0 is available)
 * aldeed:schema-index 1.1.1 (2.0.0 is available)
To update one or more of these packages, pass their names to 
`meteor update`, or just run `meteor update --all-packages`.

$ meteor update aldeed:collection2-core
**The specified packages are at their latest compatible versions.**

**Comment by nidem** [comment]
I had this issue until I followed the first steps of the README and added the npm module.

```
$ meteor npm install --save simpl-schema
$ meteor update
```

**Comment by carlosalvidrez** [comment]
Thank you for your help. I did try it, but still got the exact same error message afterwards.

**Comment by timonstr** [comment]
@carlosalvidrez probably you also have aldeed:collection2 package installed. If you want to use aldeed:collection2-core 2.0.0, you have to remove aldeed:collection2 before, then try to install as @nidem mentioned above.

**Comment by carlosalvidrez** [comment]
Will try that... thank you very much.
