### ISSUE TITLE
autoValues not working when updating with null-prototype objects

### ISSUE THREAD

**Issue by jschlieber** [aldeed/meteor-collection2-core#24]
Found this by resolving #23. Might be somehow related to #8. Think this deserves a separate issue. The following is a 99% copy paste of [this comment in #23](https://github.com/aldeed/meteor-collection2-core/issues/23#issuecomment-298976006):

Let's say we have a `Collection` with an attached schema that has a field defined with an `autoValue` function. Let's further say `doc` is an object with `Object.getPrototypeOf(doc)` equals `null` and it is valid by the schema of the `Collection`. When I do an update
```js
Collection.update({
  _id: doc._id
}, {
  $set: doc
})
```
then no matter what the `autoValue` function may return (and it will be called), the result will not appear in the updated document. But if I do the update this way:
```js
Collection.update({
  _id: doc._id
}, {
  $set: {
    ...doc
  }
})
```
where `Object.getPrototypeOf({ ...doc })` equals `{}` it works and the `autoValue` fields will be there as expected.
So, it seems collection2 doesn't like `null`-prototype objects.

**Comment by aldeed** [comment]
Why is it important to support null prototype? There are places where simpl-schema has to decide whether to recurse into an object and keep validating, or whether to treat it as some custom object. To do this check, it uses:

```js
obj === Object(obj) && Object.getPrototypeOf(obj) === Object.prototype;
```
