### ISSUE TITLE
Found both autoValue and defaultValue. Ignoring defaultValue

### ISSUE THREAD

**Issue by trymbill** [aldeed/meteor-collection2-core#26]
I've got a boolean in a SimpleSchema that should be false by default:

```{ isCompleted: {type: Boolean, defaultValue: false} }```

But I get this error:

```SimpleSchema: Found both autoValue and defaultValue options for "isCompleted". Ignoring defaultValue```

I don't have autoValue set for that key so I'm not sure where that's coming from.

```
$ meteor list
aldeed:collection2-core      2.0.1  Core package for aldeed:collection2
aldeed:schema-deny           2.0.0  Deny inserting or updating certain properties through schema options
```

```
$ npm list
[...]
└─┬ simpl-schema@0.3.0
[...]
```

**Comment by aldeed** [comment]
This was fixed in simpl-schema@0.4.0. https://github.com/aldeed/node-simple-schema/blob/master/CHANGELOG.md#040
