### ISSUE TITLE
How to get currently attached schema?

### ISSUE THREAD

**Issue by bartmichu** [aldeed/meteor-collection2-core#28]
How can I get a schema definition that is currently attached to some collection?

```
export const mySchema = new SimpleSchema({ ... });
MyColletion.attachSchema(mySchema);
```
Now, on the client side,  I would like to get some label:
```
//something like
MyCollection.getSchema().label("fieldName");
```
How can I do this?

I know I could ```import mySchema``` and use that, but it's not what I'm looking for since it requires prior knowledge of schema definition that was attached.

**Comment by dcantatore** [comment]
`MyCollection.simpleSchema()`

**Comment by bartmichu** [comment]
Exactly what I was looking for, somehow I missed it in the documentation. Thank you.
