### ISSUE TITLE
Collection2 `$set` with an array of objects

### ISSUE THREAD

**Issue by bp12345** [aldeed/meteor-collection2-core#31]
This might not be an issue, I not sure. Basically, I'm using simple-schema and colelction2 with reactjs. I have an array of Objects that I'm trying to save into a collection. I'm currently using `$push` to update my collection which works, however, I would like to use `$set` to get access to the cleaning functionality of collection2. When I use `$set` I get an array with no objects in my collection. I'm a little confused as to what is causing this. 

The collection when using `$set` looks like:
```
 {
  "_id": "ephCX8y8pt5AcqNNY",
  "userId": "yLyBjWzfbSpP5nG8h",
  "languages": []
}
```

```
const ProfileCandidateSchema = new SimpleSchema({
  userId: {
    type: String,
    regEx: SimpleSchema.RegEx.Id
  },
  languages: { type: Array, optional: true },
  'languages.$': { type: Object, optional: true },
  'languages.$.uniqueId': { type: Number, optional: true },
  'languages.$.language': { type: String, optional: true },
  'languages.$.proficiency': { type: String, optional: true }
}, {
  clean: {
    filter: true,
    autoConvert: true,
    removeEmptyStrings: true,
    trimStrings: true,
    getAutoValues: true,
    removeNullsFromArrays: true
  }
});
```

```
const updateEducationHisotry = this.state.languages.map((language) => {
  ProfileCandidate.update({
    _id: this.state.profileCandidateCollectionId
  }, {
    $set: {
      languages: [{
        language: language.language,
        uniqueId: language.uniqueId,
        proficiency: language.proficiency
      }]
    }
  }, (error, result) => {
    if (error) {
      console.log("ereer: ", error.invalidKeys);
      Bert.alert('Oops. It looks like something went wrong with the database save. Please try again or contact us.', 'danger', 'growl-top-right');
    }
    if (result) {
      Bert.alert('Languages saved.', 'success', 'growl-top-right');
    }
  })
});
```

**Comment by MaxGuitet** [comment]
It is usually not recommended to update collections directly from client. Have you considered using [mdg:validated-method](https://github.com/meteor/validated-method) in conjunction with SimpleSchema to validate your object?

**Comment by bp12345** [comment]
I tried that awhile ago but had some trouble with it. Are you suggesting this is a problem with my object or the way I'm handling it and not a problem with simple-schema or collection2. I've been trying to find a reason/solution for months and haven't found anything.

**Comment by MaxGuitet** [comment]
Not sure. What error are you getting?

The good thing with `ValidatedMethod` is that your object will be validated before the method is run.

```js
const LanguageSchema = new SimpleSchema({
  uniqueId: { type: Number, optional: true },
  language: { type: String, optional: true },
  proficiency: { type: String, optional: true },
});

const ProfileCandidateSchema = new SimpleSchema({
  userId: {
    type: String,
    regEx: SimpleSchema.RegEx.Id
  },
  languages: { type: Array, optional: true },
  'languages.$': { type: LanguageSchema, optional: true },
});

const method = new ValidatedMethod({
  name: 'yourMethodName',
  validate: new SimpleSchema(LanguageSchema)
    .extend({
      candidateId: {
        type: String
        regEx: SimpleSchema.RegEx.Id,
      },
    })
    .validator(),
  run({ candidateId, ...language }) {
    // At this point, the 'language' object should be clean
    ProfileCandidate.update({
    _id: candidateId
    }, {
      $addToSet: {
        languages: language
      },
    },
  },
});
```

**Comment by anymos** [comment]
It s  bug I just find the same thing on my side serverside 

try to $set a field not related to an array, with a document  object having an array and you can reproduce the bug server side.

workaround :{bypassCollection2:true}

which it not ideal.

No time to investiguate it more for now.

by the way is this repo still maintain ?

**Comment by bp12345** [comment]
Thanks @anymos . The problem appears to be related to the clean function. If you remove `removeNullsFromArrays: true` then `$set` works. I hope this helps you fix the problem.

**Comment by aldeed** [comment]
@anymos @bp12345 Can someone post the simplest schema and update modifier that will reproduce this issue? I'm having trouble understanding.

**Comment by aldeed** [comment]
Actually I'm pretty sure this is the same issue as https://github.com/aldeed/meteor-collection2-core/issues/35. Should be fixed in next simpl-schema release
