### ISSUE TITLE
Support whole-document updates

### ISSUE THREAD

**Issue by realyze** [aldeed/meteor-collection2-core#33]
I have a `displayableLocation` field which I compute via `autoValue` when `address` field is set (essentially adding random "jitter" to the provided address). I'm returning an object from `autoValue` like so:
```
displayableLocation: {
  type: Object,
  autoValue: function () {
    // other logic
    return {
      address: '...'
    }
  }
}
```

However when I call `MapEnitites.update({_id: entity._id}, entity)`, `autoValue` adds the `displayableLocation.address` field under a `$set` modifier so I end up with a half-modifier, half-document and collection2 reports `Expected '_id' to be a modifier operator like '$set'`.

Can I actually use whole documents with `update`?

**Comment by aldeed** [comment]
Whole-doc updates not currently supported, though you can always validate it yourself and then do the update with `bypassCollection2: true` option

**Comment by aldeed** [comment]
Moved to https://github.com/aldeed/meteor-collection2/issues/368
