### ISSUE TITLE
Array of objects bug

### ISSUE THREAD

**Issue by bp12345** [aldeed/meteor-collection2-core#35]
Hi Aldeed. I'm pretty sure this is a bug, as I can't seem to find a solution. It would be good to get some clarification. 

Please tell me what I'm missing here. When I update the Array of objects my collection updates with an empty array. I'm using [meteor-collection2-core][1] and [node-simple-schema][2]. Since it inserts an empty array, there's no error.

Path: `Method`

    testArray = [{
    	"institution": "Swinburn",
    	"uniqueId": 1501036480813,
    	"qualification": "Bachelor of Commerce",
    	"completed": "2017"
    }]
    
    ProfileCandidate.update('Ntzj6kE8qZsvSPMEP', {$set: {educationQualifications: testArray}});

Path: `Collection`

    export const ProfileCandidate = new Mongo.Collection('profileCandidate');
    
    const ProfileCandidateSchema = new SimpleSchema({
      userId: {
        type: String,
        regEx: SimpleSchema.RegEx.Id
      },
      educationQualifications: { type: Array, optional: true },
      'educationQualifications.$': { type: Object, optional: true },
      'educationQualifications.$.uniqueId': { type: Number, optional: true },
      'educationQualifications.$.institution': { type: String, optional: true },
      'educationQualifications.$.qualification': { type: String, optional: true },
      'educationQualifications.$.completed': { type: String, optional: true }
    });
    
    ProfileCandidate.attachSchema(ProfileCandidateSchema);

  [1]: https://github.com/aldeed/meteor-collection2-core
  [2]: https://github.com/aldeed/node-simple-schema

**Comment by chathuraa** [comment]
I have the same issue. When inserting.

**Comment by bp12345** [comment]
any further information on this?
