### ISSUE TITLE
Return ValidationError's from Meteor.methods

### ISSUE THREAD

**Issue by matsrietdijk** [aldeed/meteor-collection2-core#38]
Hello @aldeed,

I'm just starting to work with Meteor and your package is suggested in the guides along with `mdg:validated-method`. The documentation stated that a `ValidationError` (from `mdg:validation-error`) would be return but after scanning the source code here this doesn't seem to be the case any more, instead it now returns a `Meteor.Error` with json encoded details. How I'm using these libraries together:

I have a simple collection, with a very basic schema (using npm `simpl-schema`):

```
export const Shops = new Mongo.Collection('shops')
Shops.attachSchema(new SimpleSchema({
    name: { type: String },
    createdAt: { type: Date },
    updatedAt: { type: Date }
}))
```

And to manipulate this collection from the client-side I created the following method:

```
export const insert = new ValidatedMethod({
    name: 'shops.insert',
    validate: new SimpleSchema({
        shop: { type: Object }
    }).validator(),
    run({ shop }) {
        return Shops.insert({
            ...shop,
            createdAt: new Date(),
            updatedAt: new Date()
        })
    }
})
```

Note that I use the validation in the method to do very basic argument checks and let `Shops.insert` handle the actual object validation (because I don't want the client to supply the timestamps and wouldn't like to redefine most of the schema in the `ValidatedMethod`). 

When validation fails the client-side receives a `Meteor.Error` with status 400, a reason based on the failing field and json encoded details. What is the way to go here; Should I parse the details myself or can I somehow map the error to a `ValidationError`?

**Comment by aldeed** [comment]
See the second example here: https://github.com/aldeed/node-simple-schema/#customize-the-error-that-is-thrown
