### ISSUE TITLE
How to test when using this.userID in schema

### ISSUE THREAD

**Issue by dcantatore** [aldeed/meteor-collection2-core#40]
I am trying to write tests for a method that has inserts to a schema that rely on this.userId but as you might have guessed, that context doesn't exist on a server to server action. 

Is there a way to get the userId context that I can switch over to when something like isfromTrustedCode is true?

Otherwise is the only/best solution to extend the context all over my applications database interactions so that I can guarantee the userId context is passed in??

**Comment by aldeed** [comment]
If it's just for tests, you could mock/override `Meteor.userId()` to return some ID. I'm pretty sure `this.userId` comes from a call to `Meteor.userId()`.
