### ISSUE TITLE
Default Schema for No Matching Selector when using Multiple Schemas

### ISSUE THREAD

**Issue by WilliamT-Streamba** [aldeed/meteor-collection2-core#43]
Is it possible to define a default schema to use when no matching selector is present? I want to be able to use a default schema when performing updates so I only need to include a selector in relevant updates.

**Comment by aldeed** [comment]
Not currently possible, but someone could submit a PR to add this

**Comment by aldeed** [comment]
Moved to https://github.com/aldeed/meteor-collection2/issues/369

**Comment by rcsandell** [comment]
Bump. Fixed in #391 https://github.com/aldeed/meteor-collection2/pull/391
