### ISSUE TITLE
How do I combine Schemas using Collection2-core?

### ISSUE THREAD

**Issue by tobitech** [aldeed/meteor-collection2-core#44]
I've seen examples where Schemas are combined using [meteor-simple-schema](https://github.com/aldeed/meteor-simple-schema) how do I do that using this package? For instance when I do something like this: 
`items: {
        type: Array,
        optional: true
    },
    "items.$": {
        type: Shema.CartItem
    },`
I get an error that item items.$ requires a type. Can't I use a Schema as the type?

**Comment by aldeed** [comment]
Yes you can. You must have a typo, or `Shema.CartItem` is not yet defined in the file/line on which you're using it.
