### ISSUE TITLE
How can i use this in a package

### ISSUE THREAD

**Issue by fly19890211** [aldeed/meteor-collection2-core#45]
Hello, 
I would like to construct my app by multi separated MeteorJS packages. 
I would like to use and define this in a package 'namespace:lib'.
How can i define and use it in package for import SimpleSchema from 'simpl-schema'
and make the functionality to global just like we install under app (api.export)?

Thanks

**Comment by aldeed** [comment]
Please refer to https://guide.meteor.com/writing-atmosphere-packages.html#npm-dependencies
