### ISSUE TITLE
Allow passing options further

### ISSUE THREAD

**Issue by theodorDiaconu** [aldeed/meteor-collection2-core#47]
https://github.com/cult-of-coders/redis-oplog/issues/207

Basically, when we do client-side mutations, we need this package to not strip out the options, but pass them along. 

So what we basically need, is a way to configure this package, to allow passing options to the .insert(). Update already takes options so we're fine with that, and remove doesn't get overridden.

**Comment by theodorDiaconu** [comment]
@aldeed this is important, if you think this is ok I can create a PR for it.

**Comment by aldeed** [comment]
@theodorDiaconu Sounds fine. It might actually be possible to check `Mongo.Collection.prototype.insert.length` for a more generic solution (to see how many args it expects). If > 2, then pass options.

**Comment by aldeed** [comment]
Moved to https://github.com/aldeed/meteor-collection2/issues/370
