### ISSUE TITLE
Support complicated selectors for upserts

### ISSUE THREAD

**Issue by nyej** [aldeed/meteor-collection2-core#50]
Example:
schema: 
```
{
  createdAt: { type: Date },
  a: { type: Number },
  b: { type: Number },
  c: { type: Date, optional: true }
}
```

Code:
```
collection.upsert(
  { a: 1, b: 2, c: { $exists: false } }, 
  { 
    $setOnInsert: { createdAt: new Date() }, 
    $set: { a: 1, b: 2 }
  })
```

Basically, I want a document where a is 1, b is 2 that does not have a c field (which is a flag type field, the Date simply indicating when it was set). Instead, this gives a schema validation error that says { $exists: false } is not a Date.

It seems that the fields of the selector are being copied into the $set for validation (based on comments in the code). This obviously won't work for any field that has a mongodb keyword in its value, like the above.

**Comment by aldeed** [comment]
Yep, if the selector is complicated, the simple solution we have does not work. What it really needs to do is to implement the copying behavior exactly the way mongodb does it, but someone would have to research what this is and then implement this. I would accept a PR.

In the meantime, the workaround is to validate the data you are setting on your own prior to the upsert, and then use the `validate: false` option on your `upsert` call.

**Comment by aldeed** [comment]
Moved to https://github.com/aldeed/meteor-collection2/issues/371
