### ISSUE TITLE
Set cleaning defaults differently for insert vs update

### ISSUE THREAD

**Issue by jankapunkt** [aldeed/meteor-collection2-core#54]
Is there currently a way to globally set on/off validation options like `filter`, `autoConvert` etc.? I like for example `filter` to be `false` for all `insert` but not `update` calls.

I just see in the code

```javascript
const defaultCleanOptions = {
  filter: true,
  autoConvert: true,
  removeEmptyStrings: true,
  trimStrings: true,
  removeNullsFromArrays: false,
};
```

Is there a reason, that this is not implemented? (too complicated, effort vs. outcome, no real use case etc.)

**Comment by aldeed** [comment]
As of collection2-core 2.1.1, it will respect any defaults you set in the attached schema. See https://github.com/aldeed/simple-schema-js#set-default-cleaning-options

There is no current way to set different defaults for insert vs update, but it could be added without too much difficulty if you or anyone wants to submit a PR.

The simplest way would be new options passed to `attachSchema`:

```js
collection.attachSchema(schema, {
  defaultCleanOptions: {
    insert: { ... },
    update: { ... },
  },
});
```

And then use those when extending the options.

**Comment by aldeed** [comment]
Moved to https://github.com/aldeed/meteor-collection2/issues/372
