### ISSUE TITLE
collection.simpleSchema() requires doc argument when there are multiple schemas

### ISSUE THREAD

**Issue by j20** [aldeed/meteor-collection2-core#6]
I believe this commit broke functionality in some apps: https://github.com/aldeed/meteor-collection2-core/commit/587c0f4d33821dccef9e29fa2a28eb8bcac08956#diff-aa20ec9593194588d778c79c8821e0d1R88

My app did not change and was successfully running these versions:

```
    -aldeed:collection2@2.7.0
    -aldeed:simple-schema@1.3.3
```

After a `meteor update`, these package versions are used:

```
    +aldeed:collection2@2.9.1
    +aldeed:collection2-core@1.1.1
    +aldeed:schema-deny@1.0.1
    +aldeed:schema-index@1.0.1
    +aldeed:simple-schema@1.5.3
    (Also, Autoform is used but the version did not change--aldeed:autoform@5.8.1)
```

And it throws this error:

```
    Error: collection.simpleSchema() requires doc argument when there are multiple schemas meteor.js:880:11

    obj.prototype.simpleSchema@http://localhost:3000/packages/aldeed_collection2-core.js?b5d04a9cee2ea469306c494b472f19e5037eb8e5:154:1
    setDefaults@http://localhost:3000/packages/aldeed_autoform.js?b3aa1a45a8c57d1da1124520538d2cb9fa458509:3013:18
    autoFormCreated/<@http://localhost:3000/packages/aldeed_autoform.js?b3aa1a45a8c57d1da1124520538d2cb9fa458509:6559:12
    viewAutorun/</<@http://localhost:3000/packages/blaze.js?695c7798b7f4eebed3f8ce0cbb17c21748ff8ba8:1880:18
    Template._withTemplateInstanceFunc@http://localhost:3000/packages/blaze.js?695c7798b7f4eebed3f8ce0cbb17c21748ff8ba8:3679:12
    viewAutorun/<@http://localhost:3000/packages/blaze.js?695c7798b7f4eebed3f8ce0cbb17c21748ff8ba8:1878:1
    Blaze._withCurrentView@http://localhost:3000/packages/blaze.js?695c7798b7f4eebed3f8ce0cbb17c21748ff8ba8:2219:12
    viewAutorun@http://localhost:3000/packages/blaze.js?695c7798b7f4eebed3f8ce0cbb17c21748ff8ba8:1877:1
    Tracker.Computation.prototype._compute@http://localhost:3000/packages/tracker.js?7776276660c988c38fed448d8262b925dffb5bc3:349:5
    Tracker.Computation@http://localhost:3000/packages/tracker.js?7776276660c988c38fed448d8262b925dffb5bc3:237:5
    ... (stack track trimmed here)
```

My app is using multiple schemas like this and was fully working before the dependencies update:

```
    Products.attachSchema(SchemaA, {selector: {type: 'a'}});
    Products.attachSchema(SchemaB,   {selector: {type: 'b'  }});
```

Can you give me a hint of what 'doc' parameter it is referring to please? Is this on the autoform, when attaching the schema to a collection, etc? That way I can know where to look to solve this and further test if it's an error with this package.

**Comment by qusai87** [comment]
I think it's bug in the implementation, I checked the source code, you have to remove it and use the older version.

**Comment by psaelango** [comment]
I'm trying to do the same thing - Trying to insert two different schemas into a single collection. Just for example

Collections.js Code

Employee = new SimpleSchema ({
        EmpNo: {
          type: Number,
          label: "EmpNo"
        },
        EmpAddress: {
          type: String,
          label: "EmpAddress"
       }
});
Student = new SimpleSchema ({
        StuNo: {
          type: Number,
          label: "StuNo"
        },
        StuAddress: {
          type: String,
          label: "StuAddress"
       }
});
SampleCollection.attachSchema(Employee);//attempt[1]
SampleCollection.attachSchema(Student);//attempt[1]
/*Also I've tried*/
doc=this._id;
SampleCollection.attachSchema(Employee, doc, {selector: {type: 'a'}});//attempt[2]
SampleCollection.attachSchema(Student, doc, {selector: {type: 'b'}});//attempt[2]
Similarly in Client code

attempt[1]
{{> quickForm collection="SampleCollection" schema="Employee" id="insertEmployeeForm" type="insert"}} 
{{> quickForm collection="SampleCollection" schema="Student" id="insertStudentForm" type="insert" }}
attempt[2]
 {{> quickForm collection="SampleCollection" schema="Employee" id="insertEmployeeForm" type="insert"  doc=this selector="type:'a'"}}
{{> quickForm collection="SampleCollection" schema="Student" id="insertStudentForm" type="insert" doc=this selector="type:'b'"}}
Either way I'm getting error
Error for attempt[1] - collection.SimpleSchema() requires doc argument
Error for attempt[2] - Error - Require StuNo || EmpNo (other schema attribute)

When i googled, I came across similar errors - aldeed/meteor-collection2-core#6.

So is the issue still open?

I have one more doubt - How to mention selector in the front end code along with the quickForm??
{{> quickForm collection="SampleCollection" schema="Employee" id="insertEmployeeForm" type="insert" doc=this selector="type:'a'"}} --> Is this Correct?

**Comment by qusai87** [comment]
Hello @psaelango ,

after trying to fix it, I decide to change the way: 

I used quickform without collection and use 'meteormethod' attributre to save it in server, I think it's better way.

```
<template name="myTemplate">
     {{> quickForm schema=schema id="myTemplateRequest" type="method" meteormethod="myTemplateRequestHandler" }}
</template>
```

on clientside js: 

```
Template.myTemplate.onCreated(function(){
    var self = this;
    // default schema for the form on rendered
    Session.setDefault('templateSchema', 'schemaName');
});
Template.myTemplate.helpers({
    schema: function () {
     // you can add some logic here to select which schema to use
      return Schemas[Session.get('templateSchema')];
    }
}); 
```
on server side :

```
Meteor.methods({
    myTemplateRequestHandler: function (data) {
        var id = Requests.insert(data, {validate: false}); // I don't know if you need to validate it or not
        return id;
    }
});
```

hope it useful for you!

**Comment by nidem** [comment]
I forked the project and tested with a fix in a fork of teamnibble's autoform and it worked. The fix is here:
https://github.com/teamnibbl/meteor-autoform/pull/1/commits/7fbf7ef2d2f46fc980e9390d39455ee93b2d3859

**Comment by nidem** [comment]
Sorry, the issue is in autoform, not this repo. My bad.

**Comment by nidem** [comment]
I added a PR in aldeed/meteor-autoform to resolve the issue
